// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "../ui.h"

void ui_MotionSensorScreen_screen_init(void)
{
    ui_MotionSensorScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MotionSensorScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MotionSensorScreen, lv_color_hex(0x00FFBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MotionSensorScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_MotionSensorScreen, lv_color_hex(0x2195F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_MotionSensorScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_MotionSensorScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_MotionSensorScreen, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_accLabel = lv_label_create(ui_MotionSensorScreen);
    lv_obj_set_width(ui_accLabel, 70);
    lv_obj_set_height(ui_accLabel, 14);
    lv_obj_set_x(ui_accLabel, -26);
    lv_obj_set_y(ui_accLabel, -67);
    lv_obj_set_align(ui_accLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_accLabel, "加速度[mg]");
    lv_obj_set_style_text_align(ui_accLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_accLabel, &ui_font_GenJyuuGothic12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_accLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_accLabel, lv_color_hex(0x00FF93), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_accLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_accLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_accLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_accLabel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_angularLabel = lv_label_create(ui_MotionSensorScreen);
    lv_obj_set_width(ui_angularLabel, 60);
    lv_obj_set_height(ui_angularLabel, 28);
    lv_obj_set_x(ui_angularLabel, 28);
    lv_obj_set_y(ui_angularLabel, -44);
    lv_obj_set_align(ui_angularLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_angularLabel, "角速度[mdps]");
    lv_obj_set_style_text_align(ui_angularLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_angularLabel, &ui_font_GenJyuuGothic12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_angularLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_angularLabel, lv_color_hex(0x00FF93), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_angularLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_angularLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_angularLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_angularLabel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_magLabel = lv_label_create(ui_MotionSensorScreen);
    lv_obj_set_width(ui_magLabel, 60);
    lv_obj_set_height(ui_magLabel, 14);
    lv_obj_set_x(ui_magLabel, -30);
    lv_obj_set_y(ui_magLabel, 7);
    lv_obj_set_align(ui_magLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_magLabel, "磁力[mG]");
    lv_obj_set_style_text_align(ui_magLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_magLabel, &ui_font_GenJyuuGothic12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_magLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_magLabel, lv_color_hex(0x0071FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_magLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_magLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_magLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_magLabel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_MotionSensorScreen);
    lv_obj_set_width(ui_Button3, 20);
    lv_obj_set_height(ui_Button3, 20);
    lv_obj_set_x(ui_Button3, 50);
    lv_obj_set_y(ui_Button3, -65);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "X");

    ui_accdata1 = lv_obj_create(ui_MotionSensorScreen);
    lv_obj_remove_style_all(ui_accdata1);
    lv_obj_set_width(ui_accdata1, 80);
    lv_obj_set_height(ui_accdata1, 48);
    lv_obj_set_x(ui_accdata1, -20);
    lv_obj_set_y(ui_accdata1, -30);
    lv_obj_set_align(ui_accdata1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_accdata1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_XLabel2 = lv_label_create(ui_accdata1);
    lv_obj_set_width(ui_XLabel2, 80);
    lv_obj_set_height(ui_XLabel2, 16);
    lv_obj_set_x(ui_XLabel2, 0);
    lv_obj_set_y(ui_XLabel2, -16);
    lv_obj_set_align(ui_XLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_XLabel2, " X: ");
    lv_obj_set_style_text_font(ui_XLabel2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_YLabel2 = lv_label_create(ui_accdata1);
    lv_obj_set_width(ui_YLabel2, 80);
    lv_obj_set_height(ui_YLabel2, 16);
    lv_obj_set_align(ui_YLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_YLabel2, " Y: ");
    lv_obj_set_style_text_font(ui_YLabel2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ZLabel2 = lv_label_create(ui_accdata1);
    lv_obj_set_width(ui_ZLabel2, 80);
    lv_obj_set_height(ui_ZLabel2, 16);
    lv_obj_set_x(ui_ZLabel2, 0);
    lv_obj_set_y(ui_ZLabel2, 16);
    lv_obj_set_align(ui_ZLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ZLabel2, " Z: ");
    lv_obj_set_style_text_font(ui_ZLabel2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_angulardata1 = lv_obj_create(ui_MotionSensorScreen);
    lv_obj_remove_style_all(ui_angulardata1);
    lv_obj_set_width(ui_angulardata1, 80);
    lv_obj_set_height(ui_angulardata1, 48);
    lv_obj_set_x(ui_angulardata1, 40);
    lv_obj_set_y(ui_angulardata1, -10);
    lv_obj_set_align(ui_angulardata1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_angulardata1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_XLabel3 = lv_label_create(ui_angulardata1);
    lv_obj_set_width(ui_XLabel3, 80);
    lv_obj_set_height(ui_XLabel3, 16);
    lv_obj_set_x(ui_XLabel3, 0);
    lv_obj_set_y(ui_XLabel3, -12);
    lv_obj_set_align(ui_XLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_XLabel3, " X: ");
    lv_obj_set_style_text_font(ui_XLabel3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_YLabel3 = lv_label_create(ui_angulardata1);
    lv_obj_set_width(ui_YLabel3, 80);
    lv_obj_set_height(ui_YLabel3, 16);
    lv_obj_set_x(ui_YLabel3, 0);
    lv_obj_set_y(ui_YLabel3, 4);
    lv_obj_set_align(ui_YLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_YLabel3, " Y: ");
    lv_obj_set_style_text_font(ui_YLabel3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ZLabel3 = lv_label_create(ui_angulardata1);
    lv_obj_set_width(ui_ZLabel3, 80);
    lv_obj_set_height(ui_ZLabel3, 16);
    lv_obj_set_x(ui_ZLabel3, 0);
    lv_obj_set_y(ui_ZLabel3, 20);
    lv_obj_set_align(ui_ZLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ZLabel3, " Z: ");
    lv_obj_set_style_text_font(ui_ZLabel3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_magdata1 = lv_obj_create(ui_MotionSensorScreen);
    lv_obj_remove_style_all(ui_magdata1);
    lv_obj_set_width(ui_magdata1, 80);
    lv_obj_set_height(ui_magdata1, 48);
    lv_obj_set_x(ui_magdata1, -20);
    lv_obj_set_y(ui_magdata1, 40);
    lv_obj_set_align(ui_magdata1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_magdata1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_XLabel1 = lv_label_create(ui_magdata1);
    lv_obj_set_width(ui_XLabel1, 80);
    lv_obj_set_height(ui_XLabel1, 16);
    lv_obj_set_x(ui_XLabel1, 0);
    lv_obj_set_y(ui_XLabel1, -16);
    lv_obj_set_align(ui_XLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_XLabel1, " X: ");
    lv_obj_set_style_text_font(ui_XLabel1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_YLabel1 = lv_label_create(ui_magdata1);
    lv_obj_set_width(ui_YLabel1, 80);
    lv_obj_set_height(ui_YLabel1, 16);
    lv_obj_set_align(ui_YLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_YLabel1, " Y: ");
    lv_obj_set_style_text_font(ui_YLabel1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ZLabel1 = lv_label_create(ui_magdata1);
    lv_obj_set_width(ui_ZLabel1, 80);
    lv_obj_set_height(ui_ZLabel1, 16);
    lv_obj_set_x(ui_ZLabel1, 0);
    lv_obj_set_y(ui_ZLabel1, 16);
    lv_obj_set_align(ui_ZLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ZLabel1, " Z: ");
    lv_obj_set_style_text_font(ui_ZLabel1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sixtemp = lv_label_create(ui_MotionSensorScreen);
    lv_obj_set_width(ui_sixtemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sixtemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sixtemp, 30);
    lv_obj_set_y(ui_sixtemp, 34);
    lv_obj_set_align(ui_sixtemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sixtemp, "00.0 C");
    lv_obj_set_style_radius(ui_sixtemp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sixtemp, lv_color_hex(0x00FF93), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sixtemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_sixtemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_sixtemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sixtemp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sixtemp2 = lv_label_create(ui_MotionSensorScreen);
    lv_obj_set_width(ui_sixtemp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sixtemp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sixtemp2, 30);
    lv_obj_set_y(ui_sixtemp2, 54);
    lv_obj_set_align(ui_sixtemp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sixtemp2, "00.0 C");
    lv_obj_set_style_radius(ui_sixtemp2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sixtemp2, lv_color_hex(0x0071FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sixtemp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_sixtemp2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_sixtemp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sixtemp2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}
