/*
 * Copyright 2019 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v5.0
processor: MIMXRT1021xxxxx
package_id: MIMXRT1021DAG5A
mcu_data: ksdk2_0
processor_version: 5.0.2
board: MIMXRT1020-EVK
pin_labels:
- {pin_num: '93', pin_signal: GPIO_AD_B0_15, label: 'LCD_DC_GPIO_PIN/U11[25]/J19[2]', identifier: ENET_TXD1;LCD_DC_GPIO_PIN}
power_domains: {NVCC_GPIO: '3.3'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "fsl_gpio.h"
#include "pin_mux.h"
#include "fsl_xbara.h"
/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '101', peripheral: LPUART1, signal: RX, pin_signal: GPIO_AD_B0_07, software_input_on: Disable}
  - {pin_num: '105', peripheral: LPUART1, signal: TX, pin_signal: GPIO_AD_B0_06, software_input_on: Disable}
  - {pin_num: '93', peripheral: GPIO1, signal: 'gpio_io, 15', pin_signal: GPIO_AD_B0_15, identifier: LCD_DC_GPIO_PIN, direction: OUTPUT, software_input_on: Disable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03U */
  CLOCK_EnableClock(kCLOCK_Xbar1); 

  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_30_GPIO2_IO30, 0U);  /* 触摸中断引脚 */
  LPSPI2_InitPins();
  LPSPI4_InitPins();
  ENC_InitPins();
  // LCD BackLight PWM
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_31_FLEXPWM2_PWMB02, 0U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_31_FLEXPWM2_PWMB02, 0x10B0U);
  // Heater PWM
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_29_FLEXPWM2_PWMB03, 0U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_29_FLEXPWM2_PWMB03, 0x10B0U);  
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : LPSPI4_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void LPSPI4_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03U */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_32_LPSPI4_SCK,        /* GPIO_AD_B0_10 is configured as LPSPI1_SCK */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_AD_B0_10 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_33_LPSPI4_PCS0,       /* GPIO_AD_B0_11 is configured as LPSPI1_PCS0 */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_AD_B0_11 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_34_LPSPI4_SDO,        /* GPIO_AD_B0_12 is configured as LPSPI1_SDO */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_AD_B0_12 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_35_LPSPI4_SDI,        /* GPIO_AD_B0_13 is configured as LPSPI1_SDI */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_AD_B0_13 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_37_LPSPI4_PCS2,
      1U);
  
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_EMC_32_LPSPI4_SCK,        /* GPIO_AD_B0_10 PAD functional properties : */
      0x10B0U);                               /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Keeper
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Down
                                                 Hyst. Enable Field: Hysteresis Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_EMC_33_LPSPI4_PCS0,       /* GPIO_AD_B0_11 PAD functional properties : */
      0x10B0U);                               /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Keeper
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Down
                                                 Hyst. Enable Field: Hysteresis Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_EMC_37_LPSPI4_PCS2,
      0x10B0U);
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_EMC_34_LPSPI4_SDO,        /* GPIO_AD_B0_12 PAD functional properties : */
      0x10B0U);                               /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Keeper
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Down
                                                 Hyst. Enable Field: Hysteresis Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_EMC_35_LPSPI4_SDI,        /* GPIO_AD_B0_13 PAD functional properties : */
      0x10B0U);                               /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Keeper
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Down
                                                 Hyst. Enable Field: Hysteresis Disabled */
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : LPSPI4_DeinitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void LPSPI4_DeinitPins(void) {

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_32_GPIO3_IO00,        /* GPIO_AD_B0_10 is configured as GPIO1_IO10 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_33_GPIO3_IO01,        /* GPIO_AD_B0_11 is configured as GPIO1_IO11 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_34_GPIO3_IO02,        /* GPIO_AD_B0_12 is configured as GPIO1_IO12 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_35_GPIO3_IO03,        /* GPIO_AD_B0_13 is configured as GPIO1_IO13 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_37_GPIO3_IO05,        /* GPIO_AD_B0_13 is configured as GPIO1_IO13 */
      0U);    
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : LPSPI2_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void LPSPI2_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03U */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_10_LPSPI2_SCK,        /* GPIO_AD_B0_10 is configured as LPSPI1_SCK */
      0U);                                    /* Software Input On Field: Force input path of pad GPIO_AD_B0_10 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_12_LPSPI2_SDO,        /* GPIO_AD_B0_12 is configured as LPSPI1_SDO */
      0U);                                    /* Software Input On Field: Force input path of pad GPIO_AD_B0_12 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_13_LPSPI2_SDI,        /* GPIO_AD_B0_13 is configured as LPSPI1_SDI */
      0U);                                          /* Software Input On Field: Force input path of pad GPIO_AD_B0_13 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_11_LPSPI2_PCS0,
      0U);  
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_14_LPSPI2_PCS1,
      0U);  

  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_EMC_10_LPSPI2_SCK,        /* GPIO_AD_B0_10 PAD functional properties : */
      0x10B0U);                               /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Keeper
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Down
                                                 Hyst. Enable Field: Hysteresis Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_EMC_12_LPSPI2_SDO,        /* GPIO_AD_B0_12 PAD functional properties : */
      0x10B0U);                               /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Keeper
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Down
                                                 Hyst. Enable Field: Hysteresis Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_EMC_13_LPSPI2_SDI,        /* GPIO_AD_B0_13 PAD functional properties : */
      0x10B0U);                               /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Keeper
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Down
                                                 Hyst. Enable Field: Hysteresis Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_EMC_11_LPSPI2_PCS0,
      0x10B0U);
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_EMC_14_LPSPI2_PCS1,
      0x10B0U);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : LPSPI2_DeinitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void LPSPI2_DeinitPins(void) {

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_10_GPIO2_IO10,        /* GPIO_AD_B0_10 is configured as GPIO1_IO10 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_12_GPIO2_IO12,        /* GPIO_AD_B0_11 is configured as GPIO1_IO11 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_13_GPIO2_IO13,        /* GPIO_AD_B0_12 is configured as GPIO1_IO12 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_11_GPIO2_IO11,
      0U);
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_14_GPIO2_IO14,
      0U);  
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : LPI2C1_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void LPI2C1_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03U */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_02_LPI2C1_SCL,        /* GPIO_SD_B1_02 is configured as LPI2C4_SCL */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B1_02 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_03_LPI2C1_SDA,        /* GPIO_SD_B1_03 is configured as LPI2C4_SDA */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B1_03 */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_EMC_02_LPI2C1_SCL,        /* GPIO_SD_B1_02 PAD functional properties : */
      0xD8B0U);                               /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Enabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Keeper
                                                 Pull Up / Down Config. Field: 22K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_EMC_03_LPI2C1_SDA,        /* GPIO_SD_B1_03 PAD functional properties : */
      0xD8B0U);                               /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Enabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Keeper
                                                 Pull Up / Down Config. Field: 22K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Disabled */
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : LPI2C1_DeinitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void LPI2C1_DeinitPins(void) {

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_02_GPIO2_IO02,        /* GPIO_SD_B1_02 is configured as GPIO3_IO22 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_03_GPIO2_IO03,        /* GPIO_SD_B1_03 is configured as GPIO3_IO23 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
}

void ENC_InitPins(void)
{
    IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_07_XBAR1_INOUT07, 1U); 	//A相
    IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_09_XBAR1_INOUT09, 1U); 	//B相
    IOMUXC_GPR->GPR6 = ((IOMUXC_GPR->GPR6 &
    (~(IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_7_MASK | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_9_MASK )))
      | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_7(0x00U) 
      | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_9(0x00U) 
    );
    XBARA_SetSignalsConnection(XBARA, kXBARA1_InputIomuxXbarInout09, kXBARA1_OutputEnc1PhaseAInput); 
    XBARA_SetSignalsConnection(XBARA, kXBARA1_InputIomuxXbarInout07, kXBARA1_OutputEnc1PhaseBInput);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_07_XBAR1_INOUT07, 0x10B0U); 
    IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_09_XBAR1_INOUT09, 0x10B0U);
    
    IOMUXC_SetPinMux(               // EC11 Key
    IOMUXC_GPIO_EMC_05_GPIO2_IO05,       
    0U);                                    
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
