// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
extern lv_obj_t * ui_mainScreen;
void ui_event_TempHumiButton(lv_event_t * e);
extern lv_obj_t * ui_TempHumiButton;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label1;
void ui_event_LightSensorButton(lv_event_t * e);
extern lv_obj_t * ui_LightSensorButton;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label2;
void ui_event_MotionSensorButton(lv_event_t * e);
extern lv_obj_t * ui_MotionSensorButton;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label3;
void ui_event_SetupButton(lv_event_t * e);
extern lv_obj_t * ui_SetupButton;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label4;
// SCREEN: ui_TempHumiScreen
void ui_TempHumiScreen_screen_init(void);
extern lv_obj_t * ui_TempHumiScreen;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_TempLabel;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_HumiLabel;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label7;
// SCREEN: ui_LightScreen
void ui_LightScreen_screen_init(void);
extern lv_obj_t * ui_LightScreen;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_BrightnessLabel;
void ui_event_Arc1(lv_event_t * e);
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_AdjustBrightnessLabel;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label9;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
// SCREEN: ui_MotionSensorScreen
void ui_MotionSensorScreen_screen_init(void);
extern lv_obj_t * ui_MotionSensorScreen;
extern lv_obj_t * ui_accLabel;
extern lv_obj_t * ui_angularLabel;
extern lv_obj_t * ui_magLabel;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_accdata1;
extern lv_obj_t * ui_XLabel2;
extern lv_obj_t * ui_YLabel2;
extern lv_obj_t * ui_ZLabel2;
extern lv_obj_t * ui_angulardata1;
extern lv_obj_t * ui_XLabel3;
extern lv_obj_t * ui_YLabel3;
extern lv_obj_t * ui_ZLabel3;
extern lv_obj_t * ui_magdata1;
extern lv_obj_t * ui_XLabel1;
extern lv_obj_t * ui_YLabel1;
extern lv_obj_t * ui_ZLabel1;
extern lv_obj_t * ui_sixtemp;
extern lv_obj_t * ui_sixtemp2;
// SCREEN: ui_SetupScreen
void ui_SetupScreen_screen_init(void);
extern lv_obj_t * ui_SetupScreen;
void ui_event_AdjustTempSlider(lv_event_t * e);
extern lv_obj_t * ui_AdjustTempSlider;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Chart1;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_sensor_png);    // assets\sensor.png
LV_IMG_DECLARE(ui_img_light_png);    // assets\light.png
LV_IMG_DECLARE(ui_img_sensor2_png);    // assets\sensor2.png
LV_IMG_DECLARE(ui_img_setup_png);    // assets\setup.png
LV_IMG_DECLARE(ui_img_temperature_png);    // assets\temperature.png
LV_IMG_DECLARE(ui_img_humidity_png);    // assets\humidity.png

LV_FONT_DECLARE(ui_font_font14);
LV_FONT_DECLARE(ui_font_GenJyuuGothic12);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
