// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void TempHumiButton_cb(lv_event_t * e);
void LightSensorButton_cb(lv_event_t * e);
void MotionSensorButton_cb(lv_event_t * e);
void SetupButton_cb(lv_event_t * e);
void Button1_cb(lv_event_t * e);
void updateBackLight(lv_event_t * e);
void Button2_cb(lv_event_t * e);
void switchMode(lv_event_t * e);
void Button3_cb(lv_event_t * e);
void updateSetPoint(lv_event_t * e);
void Button4_cb(lv_event_t * e);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
