// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _UI_COMP_DATA_H
#define _UI_COMP_DATA_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT data
#define UI_COMP_DATA_DATA 0
#define UI_COMP_DATA_XLABEL 1
#define UI_COMP_DATA_YLABEL 2
#define UI_COMP_DATA_ZLABEL 3
#define _UI_COMP_DATA_NUM 4
lv_obj_t * ui_data_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
