// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT data

lv_obj_t * ui_data_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_data;
    cui_data = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_data);
    lv_obj_set_width(cui_data, 80);
    lv_obj_set_height(cui_data, 48);
    lv_obj_set_x(cui_data, -20);
    lv_obj_set_y(cui_data, -30);
    lv_obj_set_align(cui_data, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_data, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_XLabel;
    cui_XLabel = lv_label_create(cui_data);
    lv_obj_set_width(cui_XLabel, 80);
    lv_obj_set_height(cui_XLabel, 16);
    lv_obj_set_x(cui_XLabel, 0);
    lv_obj_set_y(cui_XLabel, -16);
    lv_obj_set_align(cui_XLabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_XLabel, " X: ");
    lv_obj_set_style_text_font(cui_XLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_YLabel;
    cui_YLabel = lv_label_create(cui_data);
    lv_obj_set_width(cui_YLabel, 80);
    lv_obj_set_height(cui_YLabel, 16);
    lv_obj_set_align(cui_YLabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_YLabel, " Y: ");
    lv_obj_set_style_text_font(cui_YLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ZLabel;
    cui_ZLabel = lv_label_create(cui_data);
    lv_obj_set_width(cui_ZLabel, 80);
    lv_obj_set_height(cui_ZLabel, 16);
    lv_obj_set_x(cui_ZLabel, 0);
    lv_obj_set_y(cui_ZLabel, 16);
    lv_obj_set_align(cui_ZLabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_ZLabel, " Z: ");
    lv_obj_set_style_text_font(cui_ZLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_DATA_NUM);
    children[UI_COMP_DATA_DATA] = cui_data;
    children[UI_COMP_DATA_XLABEL] = cui_XLabel;
    children[UI_COMP_DATA_YLABEL] = cui_YLabel;
    children[UI_COMP_DATA_ZLABEL] = cui_ZLabel;
    lv_obj_add_event_cb(cui_data, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_data, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_data_create_hook(cui_data);
    return cui_data;
}

